# -*- coding: utf-8 -*-
"""KenbroProject.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o1gBEPQaPaK3ad3FteKML3nwYytw-5M0
"""

import pandas as pd

data = pd.read_csv('/content/sport_data.csv')

# Pre-processing

# Change sex for binary
data['Sex'].replace(['Female','Male'],[0,1], inplace=True)

# Import ML libraries

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

from sqlalchemy.sql.expression import column
X=data.drop(columns='Sport')

y= data.drop(columns=['Age','Height','Sex'])

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2)

# Build Machine Learning

clf = DecisionTreeClassifier()
clf.fit(X_train,y_train)

# Test ML Model

test= clf.predict(X_test)

# Check model performance
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

accuracy = accuracy_score(y_test,test)
accuracy # is better than luck

# Fake Data
new_student=clf.predict([[15,4,1]])

new_student

# Save Model
# from joblib import dump
# dump(clf,'djangoML.joblib')